# Generated by Django 5.2.8 on 2025-11-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Similares', '0003_venta_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(related_name='ventas', to='app_Similares.producto'),
        ),
    ]
