# Generated by Django 5.2.8 on 2025-11-16 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Similares', '0004_venta_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_Similares.proveedor'),
            preserve_default=False,
        ),
    ]
